sudo: false

language: go

go:
  - 1.6

python:
  - 2.7
  - 3.5

script:
  - echo "[build]" >> .plzconfig.local
  - echo "path = $PATH" >> .plzconfig.local
  - echo "[go]" >> .plzconfig.local
  - echo "goroot = $GOROOT" >> .plzconfig.local
  - echo "[cpp]" >> .plzconfig.local
  - echo "cctool = g++-4.8" >> .plzconfig.local
  - echo "defaultoptcflags = --std=c++11 -O2 -DNDEBUG" >> .plzconfig.local
  - echo "[proto]" >> .plzconfig.local
  - echo "protoctool = ${HOME}/protoc" >> .plzconfig.local
  - ./bootstrap.sh --plain_output

before_install:
  - ./.travis_install.sh

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - libunittest++-dev
      - binutils
      - clang
      - gcc-4.8
      - g++-4.8
      - unzip

install:
  - pip install --user cffi>=1.5.0

git:
  depth: 3

cache:
  directories:
    - $HOME/protoc
