sudo: false

language: go

go:
  - 1.6

script:
  - echo "[please]" > .plzconfig.local
  - echo "pypylocation = ${HOME}/pypy/bin/libpypy-c.so"
  - echo "[build]" >> .plzconfig.local
  - echo "path = $PATH" >> .plzconfig.local
  - echo "[go]" >> .plzconfig.local
  - echo "goroot = $GOROOT" >> .plzconfig.local
  - echo "[cpp]" >> .plzconfig.local
  - echo "cctool = g++-4.8" >> .plzconfig.local
  - echo "[proto]" >> .plzconfig.local
  - echo "protoctool = ${HOME}/protoc" >> .plzconfig.local
  - echo "defaultoptcflags = --std=c++11 -O2 -DNDEBUG" >> .plzconfig.local
  - PATH="$PATH:${HOME}/pypy/bin" ./bootstrap.sh --plain_output

before_install:
  - ./.travis_install.sh

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - libunittest++-dev
      - binutils
      - clang
      - gcc-4.8
      - g++-4.8
      - unzip

install:
  - true

git:
  depth: 3

cache:
  directories:
    - $HOME/pypy
    - $HOME/protoc
