version: 2
jobs:
   build-linux:
     working_directory: ~/please
     docker:
       - image: thoughtmachine/please_ubuntu:latest
     environment:
       PLZ_ARGS: "-p --profile ci"
       PLZ_COVER: "cover"
     steps:
       - checkout
       - restore_cache:
           key: bootstrap-linux-main-{{ checksum "bootstrap.sh" }}
       - restore_cache:
           key: go-linux-main-{{ checksum "third_party/go/BUILD" }}
       - restore_cache:
           key: python-linux-main-{{ checksum "third_party/python/BUILD" }}
       - run:
           name: Bootstrap & Build
           command: ./bootstrap.sh --exclude no_circleci --test_results_file plz-out/results/please/test_results.xml
       - store_test_results:
           path: plz-out/results
       - run:
           name: Lint
           command: ./tools/misc/ci_lint.py
       - run:
           name: Package
           command: |
             ./plz-out/bin/src/please build //package:all --exclude asc -p &&
             mkdir /tmp/artifacts &&
             mv plz-out/gen/package/*.deb plz-out/gen/package/*.tar.gz /tmp/artifacts
       - store_artifacts:
           path: /tmp/artifacts
       - store_artifacts:
           path: plz-out/log
       - save_cache:
           key: bootstrap-linux-main-{{ checksum "bootstrap.sh" }}
           paths: [ ".bootstrap" ]
       - save_cache:
           key: go-linux-main-{{ checksum "third_party/go/BUILD" }}
           paths: [ ".plz-cache/third_party/go" ]
       - save_cache:
           key: python-linux-main-{{ checksum "third_party/python/BUILD" }}
           paths: [ ".plz-cache/third_party/python" ]


   build-linux-alt:
     working_directory: ~/please
     docker:
       - image: thoughtmachine/please_ubuntu_alt:latest
     environment:
       PLZ_ARGS: "-p --profile ci"
     steps:
       - checkout
       - restore_cache:
           key: bootstrap-linux-alt-{{ checksum "bootstrap.sh" }}
       - restore_cache:
           key: go-linux-alt-{{ checksum "third_party/go/BUILD" }}
       - restore_cache:
           key: python-linux-alt-{{ checksum "third_party/python/BUILD" }}
       - run:
           name: Bootstrap & Build
           command: ./bootstrap.sh --exclude no_circleci --test_results_file plz-out/results/please/test_results.xml
       - store_test_results:
           path: plz-out/results
       - store_artifacts:
           path: plz-out/log
       - run:
           name: Lint
           command: ./tools/misc/ci_lint.py
       - save_cache:
           key: bootstrap-linux-alt-{{ checksum "bootstrap.sh" }}
           paths: [ ".bootstrap" ]
       - save_cache:
           key: go-linux-alt-{{ checksum "third_party/go/BUILD" }}
           paths: [ ".plz-cache/third_party/go" ]
       - save_cache:
           key: python-linux-alt-{{ checksum "third_party/python/BUILD" }}
           paths: [ ".plz-cache/third_party/python" ]

   build-darwin:
      macos:
        xcode: "9.0"
      environment:
        PLZ_ARGS: "-p --profile ci --exclude pip"
      steps:
       - checkout
       - restore_cache:
           key: bootstrap-darwin-go110-{{ checksum "bootstrap.sh" }}
       - restore_cache:
           key: go-darwin-go110-{{ checksum "third_party/go/BUILD" }}
       - restore_cache:
           key: python-darwin-py370-{{ checksum "third_party/python/BUILD" }}
       - restore_cache:
           key: homebrew-v1
       - run:
           name: Install deps
           command: brew install go@1.10 unittest-cpp nasm pkg-config && brew upgrade python
       - run:
           name: Bootstrap & Build
           command: ./bootstrap.sh --exclude no_circleci --test_results_file plz-out/results/please/test_results.xml
       - store_test_results:
           path: plz-out/results
       - store_artifacts:
           path: plz-out/log
       - run:
           name: Package
           command: |
             ./plz-out/bin/src/please build //package:all --exclude asc --exclude deb -p &&
             mkdir /tmp/artifacts &&
             mv plz-out/gen/package/*.tar.gz /tmp/artifacts
       - store_artifacts:
           path: /tmp/artifacts
       - save_cache:
           key: homebrew-v1
           paths: [ "/usr/local/Homebrew" ]
       - save_cache:
           key: bootstrap-darwin-go110-{{ checksum "bootstrap.sh" }}
           paths: [ ".bootstrap" ]
       - save_cache:
           key: go-darwin-go110-{{ checksum "third_party/go/BUILD" }}
           paths: [ ".plz-cache/third_party/go" ]
       - save_cache:
           key: python-darwin-py370-{{ checksum "third_party/python/BUILD" }}
           paths: [ ".plz-cache/third_party/python" ]

workflows:
  version: 2
  build-all:
    jobs:
      - build-linux
      - build-linux-alt
      - build-darwin
