version: 2
jobs:
   build:
     working_directory: ~/please
     docker:
       - image: thoughtmachine/please:latest
     steps:
       - checkout
       - run: ./bootstrap.sh --test_results_file $CIRCLE_TEST_REPORTS/please/results.xml
