version: 2
jobs:
   build:
     working_directory: ~/please
     docker:
       - image: thoughtmachine/please_ubuntu:latest
     steps:
       - checkout
       - run: ./bootstrap.sh -p --test_results_file $CIRCLE_TEST_REPORTS/please/results.xml
       - run: ./plz-out/bin/src/please build -p //package:all
       - run: mv plz-out/gen/package/*.deb plz-out/gen/package/*.tar.gz $CIRCLE_ARTIFACTS
